-- =====================================================
-- COMPRA SPEED
-- BASE DE DATOS
-- =====================================================


create table if not exists public.products (

    id bigint generated by default as identity primary key,

    name text not null,

    price numeric not null default 0,

    old_price numeric,

    category text not null default 'Otros',

    image text,

    images jsonb not null default '[]'::jsonb,

    description text default '',

    stock integer not null default 0,

    active boolean not null default true,

    featured boolean not null default false,

    badge text default '',

    created_at timestamptz not null default now()

);


-- =====================================================
-- RLS
-- =====================================================

alter table public.products
enable row level security;


-- =====================================================
-- ELIMINAR POLÍTICAS ANTIGUAS
-- =====================================================

drop policy if exists
"Public can view active products"
on public.products;


drop policy if exists
"Authenticated can view products"
on public.products;


drop policy if exists
"Authenticated can insert products"
on public.products;


drop policy if exists
"Authenticated can update products"
on public.products;


drop policy if exists
"Authenticated can delete products"
on public.products;


-- =====================================================
-- PÚBLICO
-- SOLO PRODUCTOS ACTIVOS
-- =====================================================

create policy
"Public can view active products"

on public.products

for select

to anon

using (
    active = true
);


-- =====================================================
-- USUARIOS AUTENTICADOS
-- =====================================================

create policy
"Authenticated can view products"

on public.products

for select

to authenticated

using (
    true
);


create policy
"Authenticated can insert products"

on public.products

for insert

to authenticated

with check (
    true
);


create policy
"Authenticated can update products"

on public.products

for update

to authenticated

using (
    true
)

with check (
    true
);


create policy
"Authenticated can delete products"

on public.products

for delete

to authenticated

using (
    true
);


-- =====================================================
-- STORAGE
-- =====================================================

insert into storage.buckets (
    id,
    name,
    public
)

values (
    'productos',
    'productos',
    true
)

on conflict (
    id
)

do update set
    public = true;


-- =====================================================
-- STORAGE POLICIES
-- =====================================================

drop policy if exists
"Public can view product images"
on storage.objects;


drop policy if exists
"Authenticated can upload product images"
on storage.objects;


drop policy if exists
"Authenticated can update product images"
on storage.objects;


drop policy if exists
"Authenticated can delete product images"
on storage.objects;


create policy
"Public can view product images"

on storage.objects

for select

to public

using (
    bucket_id = 'productos'
);


create policy
"Authenticated can upload product images"

on storage.objects

for insert

to authenticated

with check (
    bucket_id = 'productos'
);


create policy
"Authenticated can update product images"

on storage.objects

for update

to authenticated

using (
    bucket_id = 'productos'
)

with check (
    bucket_id = 'productos'
);


create policy
"Authenticated can delete product images"

on storage.objects

for delete

to authenticated

using (
    bucket_id = 'productos'
);
